### ISSUE TITLE
Voortgang week 1

### ISSUE THREAD

**Issue by TM11153431** [nigelvanherwijnen/programmeerproject#1]
Hey Nigel!

Let er goed op je dat je MVP het **minimale** is wat je in gaat leveren. Op het moment staan er zes visualisaties in je MVP, ik zou dit op 3 verschillende en 2 interactieve elementen houden. Als je je focust op een kleiner MVP en daarna pas de extra visualisaties gaat doen, lijkt mij dat wat prettiger.

Daarnaast heb je op het moment ook alleen nog lege HTML bestanden ingeleverd. Ik zou er wel voor zorgen om zo snel mogelijk in ieder geval een werkende dataset in javascript te kunnen accessen en hier visualisaties mee te kunnen maken.

**Comment by nigelvanherwijnen** [comment]
Hoi!

Mijn MVP is inderdaad wat ambitieus. Ik zal het aanpassen naar de pagina met de datamap. Daar staan 3 visualisaties op met 2 interactieve elementen, dus dan is dat in ieder geval genoeg. Dit zeker met de gedachte in het achterhoofd dat ik nog geen data heb kunnen inladen in javascript. 

Gisteren heb ik, eindelijk, de benodigde data netjes in CSV bestanden gevonden en opgeschoond. Nu kan ik dus beginnen met omzetten naar JSON en het maken van de plotjes.

**Comment by nigelvanherwijnen** [comment]
MVP is kleiner gemaakt en bijbehorende werkende dataset is ingeladen.
